---
- name: "Setup CTFd"
  hosts: all
  remote_user: root
  become: true # In case remote_user is overwritten
  vars:
    domain: "ctfd.kalmarunionen.dk"
    email: "magnusgsvend@gmail.com"
  tasks:
    - name: Setup needed packages
      ansible.builtin.apt:
        pkg:
          - certbot
        state: present
        update_cache: true
    - name: Get get_docker
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: ./get_docker.sh
        mode: "755"
    - name: Install docker
      ansible.builtin.command:
        cmd: bash get_docker.sh
        creates: /usr/bin/docker
    - name: Download ctfd
      ansible.builtin.git:
        repo: https://github.com/CTFd/CTFd.git
        dest: /srv/ctfd
        version: master
    - name: Obtain SSL certificate
      ansible.builtin.command:
        cmd: certbot certonly --standalone -m "{{ email }}" --agree-tos --noninteractive --domain "{{ domain }}"
        creates: /etc/letsencrypt/live/{{ domain }}/privkey.pem
      when: local is undefined
    - name: Edit docker-compose to include our SSL cert and key
      ansible.builtin.blockinfile:
        path: /srv/ctfd/docker-compose.yml
        insertafter: "./conf/nginx/http.conf:/etc/nginx/nginx.conf"
        block: |4
                  - /etc/letsencrypt/live/{{ domain }}/privkey.pem:/etc/nginx/ssl/privkey.pem
                  - /etc/letsencrypt/live/{{ domain }}/fullchain.pem:/etc/nginx/ssl/cert.pem
      when: local is undefined
    - name: Edit docker-compose to also listen on port 443
      ansible.builtin.blockinfile:
        marker_begin: Start port
        marker_end: End port
        path: /srv/ctfd/docker-compose.yml
        insertafter: "80:80"
        block: |4
                  - 443:443
    - name: "Upload nginx.conf"
      ansible.builtin.template:
        src: ./nginx.conf
        dest: /srv/ctfd/conf/nginx/http.conf
        mode: "755"
    - name: Start CTFd
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /srv/ctfd
        creates: /srv/ctfd/.data
