---
name: tests
on:
  workflow_dispatch:
  push:
permissions:
  contents: read
  pull-requests: read
jobs:
  ghidra:
    runs-on: macos-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Install ansible
        run: python3 -m pip install --upgrade --user ansible
      - name: Add ansible to path
        run: echo "/Users/runner/Library/Python/3.11/bin" >> $GITHUB_PATH
      - name: Run vagrant
        run: vagrant up ghidra
  lumen:
    runs-on: macos-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Install ansible
        run: python3 -m pip install --upgrade --user ansible
      - name: Add ansible to path
        run: echo "/Users/runner/Library/Python/3.11/bin" >> $GITHUB_PATH
      - name: Run vagrant
        run: vagrant up lumen
  ctfd:
    runs-on: macos-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Install ansible
        run: python3 -m pip install --upgrade --user ansible
      - name: Add ansible to path
        run: echo "/Users/runner/Library/Python/3.11/bin" >> $GITHUB_PATH
      - name: Run vagrant
        run: vagrant up ctfd
