---
name: tests
on:
  workflow_dispatch:
  push:
permissions:
  contents: read
  pull-requests: read
jobs:
  ghidra:
    runs-on: macos-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install ansible
        run: python3 -m pip install --upgrade --user ansible
      - name: Run vagrant
        run: vagrant up ghidra
  lumen:
    runs-on: macos-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install ansible
        run: python3 -m pip install --upgrade --user ansible
      - name: Run vagrant
        run: vagrant up ghidra
  ctfd:
    runs-on: macos-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install ansible
        run: python3 -m pip install --upgrade --user ansible
      - name: Run vagrant
        run: vagrant up ghidra
